name: Urubu do pix 

#Gatilho , inicio do script
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# o que fazer quando o agendamento for atvd
jobs:
  check-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o c√≥digo
        uses: actions/checkout@v3
      - name: Chmod
        run: chmod +x ./check_site.sh
      - name: Executar o script
        run: ./check_site.sh 
